### PR TITLE
Fix PHP 8.1 deprecation notice

### PR DESCRIPTION
**Pull request by odan**
See #220

### CODE REVIEW

**Comment by lulco** [comment]
Thank you for contribution! Can you please add info to changelog and if it works with php 8.1 add also this version to readme

**Comment by odan** [comment]
I just added the info to the README and changelog.
It would be nice to have Github Action for multiple PHP versions to test it automatically.

**Comment by lulco** [comment]
Thanks.
Yeah, I was thinking it is configured correctly, but probably it is not :-/ When I create PR it works because I'm not in fork.
Any idea why it is not working for your PRs?

For example: https://github.com/lulco/phoenix/blob/master/.github/workflows/phpunit.yml
```
on:
  push:
  pull_request:
    branches:
      - '**:**'
```

**Comment by lulco** [comment]
OK maybe I got it. Please try to merge master to your branches and github actions should run. Also add version 8.1 to matrix in:
- https://github.com/lulco/phoenix/blob/master/.github/workflows/composer.yml
- https://github.com/lulco/phoenix/blob/master/.github/workflows/phpunit.yml
- https://github.com/lulco/phoenix/blob/master/.github/workflows/syntax_checker.yml

You can try it also in https://github.com/lulco/phoenix/blob/master/.github/workflows/phpstan.yml but there were some problems in php 8.0

**Comment by odan** [comment]
I do this by adding `on: [ push, pull_request ]` to my github actions files. [Example](https://github.com/odan/slim4-skeleton/blob/master/.github/workflows/build.yml#L3)

**Comment by odan** [comment]
The github actions build process starts now. But now there is another deprecation warning from a Composer or `friendsofphp/php-cs-fixer` sub-dependency in `justinrainbow/json-schema`. I think this can be ignored, because it's just a dev-dependency.

```
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in 
phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
```

See here: https://github.com/justinrainbow/json-schema/issues/656

**Comment by lulco** [comment]
I don’t think this notice is a problem here. It is problably some composer dependencies problem in composer itself. 

But some packages cannot be installed on php8.1 because they just don’t support it yet. We could setup allow failure for php8.1 but without running php unit tests and php stan we cannot be sure it works well

**Comment by lulco** [comment]
@odan can you create new PR with cherry picked fix in PdoAdapter and changelog.md? I will merge it into master. Than you can use dev-master and if it will be stable, we can release new version. This PR with failing PHP 8.1 tests will be on hold for now

**Pull request closed without merging**
