### PR TITLE
Added support for PHP 8.2

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by mbolli** [comment]
hey @lulco, would be nice if this gets merged soon :)

**Comment by lulco** [comment]
Hi @mbolli, thanks for ping :) it didn't work back in June, because of some dependencies, but now it seems it works, so I'll merge it. Can you please check dev-master then?

**Comment by mbolli** [comment]
that was fast! yes I can check dev-master, although on PHP 8.2-RC5 it already worked without issue for me (when using --ignore-platform-reqs on install).

**Comment by mbolli** [comment]
Looks good to me, thanks!

**Pull request merged**
