### PR TITLE
Added unique constraints support

### PR DESCRIPTION
**Pull request by aksafan**
Rethought unique constraints support.

Added auto tests:
image

as well as manual testing:
image
image

### CODE REVIEW

**Comment by lulco** [comment]
Hi @aksafan, thank you. I’ll check it later, but first view looks good to me. I just want to confirm my thougths - you implemented it back compatible, so we can use unique columns and this new feature together, right?

Also please fix the tests:
- phpstan - just add some missing typehints
- composer outdated - just add —ignore for phpunit for now (we have to support php 7.4)

**Comment by lulco** [comment]
How is it stored in database “information schema”? I'm missing the dump part implementation where we are creating migration from db structure. Is it possible to difference between unique index and unique constraint?

**Comment by aksafan** [comment]
> Hi @aksafan, thank you. I’ll check it later, but first view looks good to me. I just want to confirm my thougths - you implemented it back compatible, so we can use unique columns and this new feature together, right?
> 
> Also please fix the tests:
> 
>     * phpstan - just add some missing typehints
> 
>     * composer outdated - just add —ignore for phpunit for now (we have to support php 7.4)

Hey @lulco, 

I've fixed PHPStan errors and added phpunit to ignore.

**Comment by lulco** [comment]
Thanks, what about this?

> How is it stored in database “information schema”? I'm missing the dump part implementation where we are creating migration from db structure. Is it possible to difference between unique index and unique constraint?

**Comment by aksafan** [comment]
> How is it stored in database “information schema”? I'm missing the dump part implementation where we are creating migration from db structure. Is it possible to difference between unique index and unique constraint?

[Added](https://github.com/lulco/phoenix/pull/289/commits/85d8bcd2d3221af5c3da174b0336bf48ebbd2f58) support for unique constraints for dumps.
As for the difference - it exists for postgres:
image
and will be the same for mysql:
image

**Comment by aksafan** [comment]
> I just want to confirm my thougths - you implemented it back compatible, so we can use unique columns and this new feature together, right?

Yes, it could work together, even added tests for it (e.g. [here](https://github.com/lulco/phoenix/pull/289/files#diff-fc248cba14480627119e98da7fb183a78e02640fd5b949b75704901c0420b53dR380)).

**Comment by aksafan** [comment]
> Thanks, what about this?
> 
> > How is it stored in database “information schema”? I'm missing the dump part implementation where we are creating migration from db structure. Is it possible to difference between unique index and unique constraint?

Needed a bit of time to handle that.

**Comment by aksafan** [comment]
Hey @lulco,

Can you please run github actions to check if everything is okay?

**Comment by aksafan** [comment]
> Hey @lulco,
> 
> Can you please run github actions to check if everything is okay?

I've fixed last PHPStan error.
Now everything should be [good](https://github.com/lulco/phoenix/pull/289/files#diff-31d5779853cb2cca211bd4b2ba021966b59c74a9c8c5d00f84194eda5e50c776R167).

**Comment by bc-anton-k** [comment]
Hey @lulco,

I've fixed all checks and your suggestions.

This being said, I wonder, is there anything more left to be done for this to be merged and released?

**Pull request merged**
