### PR TITLE
Fixed bug unescaped column value. 'b'0'' -> 'b\'0\''

### PR DESCRIPTION
**Pull request by fishus**
While doing the dump, I noticed a syntax error in the resulting file. In the value of a field of type bit, quotes in the value were not escaped. This fixes this bug.

### CODE REVIEW

**Comment by lulco** [comment]
This will add backslash also to double quoted, right? I am not sure it is correct in this context.

**Comment by fishus** [comment]
> This will add backslash also to double quoted, right? I am not sure it is correct in this context.

I agree that escaping only single quotes is enough here.

**Comment by lulco** [comment]
Sorry, one more thing: please update changelog.md and we can merge it

**Comment by lulco** [comment]
Version in changelog will be added when tag will be created. I ll fix it in release. Thanks for contribution!

**Pull request merged**
